#### This notebook will dive into the most important features of the matrix determinant.

#### 1) For matrix that is upper triangular (U), lower triangular ( L ) or diagonal, the rule applies:

- determinant is calculated as the product of the numbers on the diagonal

In [1]:
# consider the matrix U 
import numpy as np

mat_1 = np.array([[1,5,2],[0,2,4],[0,0,5]])
print(mat_1)

[[1 5 2]
 [0 2 4]
 [0 0 5]]


In [23]:
det_A = mat_1[0][0] * mat_1[1][1] * mat_1[2][2]
print(det_A)

10


#### 2) For matrix that has 2 rows or columns as a combination, 3rd row/column - > determinant = **0**


In [183]:
row_1 = np.array([[0,1,2,3]]).reshape(4,)
stack = np.arange(12).reshape(3,4)

matrix_stack = np.vstack([row_1,stack])

In [184]:
det_stack = np.linalg.det(matrix_stack)
print(det_stack)

0.0


### Det = **0**

#### 3) For matrix that has one of the rows/columns same -> determinant = **0**

In [ ]:
zeros = np.zeros(4).reshape(-3,4)
matrix_2 = np.arange(12).reshape(3,4)
print(zeros,matrix_2)

print(zeros.shape,matrix_2.shape)

[[0. 0. 0. 0.]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(1, 4) (3, 4)


If we stack and make last column with zeros only:

In [121]:
matrix_2 = np.vstack([matrix_2,zeros])
matrix_2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 0.,  0.,  0.,  0.]])

### Lets confirm the theory:

In [ ]:
det_matrix_2 = np.linalg.det(matrix_2)
print(det_matrix_2) 

0.0


#### **0**