#### In this notebook I explore how can I calcualte matrix determinant ( det(A) ) for different Matrix shapes without using popular python library **Sympy**

In [556]:
import numpy as np

### First I will start with some basic exaples with square matrix just to refresh some basic rules:

- For square matrix A, of shape 2,2 -> det(A) = a*d - b*c 

[ [ 1 , 2 ], [ 3 , 4 ]]  


In [557]:
rng = np.random.randint(-3,6,size=4)
matrix_1 = np.array(rng).reshape(2,2)
matrix_1

array([[ 2, -3],
       [ 2,  3]], dtype=int32)

In [558]:
det_A = matrix_1[0][0]*matrix_1[1][1]-matrix_1[0][1]*matrix_1[1][0]
round(det_A)

12

Now lets compare the det_A with numpy built in np.linalg.det for determinant calculation

In [559]:
det_A_np = np.linalg.det(matrix_1)
round(det_A_np)

12

I get the same result.

What about more complex matrix? For the matrix A of shape n * n, we calculate det(A) with the following rule of **Cofactor** -> **C**

By using the **cofactor**, we can calculate determinant of the given matrix by rows or columns. 

i - row

j - colum

Cij = (-1)^i+j * (everything except the numbers in i-th row and j-th column)

### For this example consider the following matrix:

In [560]:
A = np.array([[0,0,1,0,0],[2,4,2,5,3],[1,0,3,0,0],[3,2,4,1,5],[4,0,5,2,0]])

In [561]:
# matrix of shape 5,5
A.shape

(5, 5)

The best practice is to choose the row/column where we have the most **0's**

- I will start with row 1, column 3 (a13)

- I will not use literal values but slice the matrix

In [562]:
det_A = A[0][2] * (1)**(1+3) * A[1:,[0,1,3,4]] # This is called minor
det_A


array([[2, 4, 5, 3],
       [1, 0, 0, 0],
       [3, 2, 1, 5],
       [4, 0, 2, 0]])

Now, applying the same rule, we see that 2nd row has 3 zeros in it. Following, i will start with 2nd row and 1st column.

Also I will explicitly define the minor before final det_A calculation

In [563]:
det_A
a21= det_A[1][0]
minor2 = det_A[[0,2,3],:][:, [1,2,3]]
print(minor2)

det_A = a21*(-1)**(1+2)*minor2

[[4 5 3]
 [2 1 5]
 [0 2 0]]


In [564]:
#det_A
print(det_A)

[[-4 -5 -3]
 [-2 -1 -5]
 [ 0 -2  0]]


Looking for the row/column with most zeros, we see that last [-1] row has 2 zeros. Lets resolve the determinant with element a_32 (third row,2nd column):

In [565]:
# calculate the minor and a_32 first:

a32 = det_A[-1][1]
minor3 = det_A[0:2:,:][:,[0,-1]]
print(minor3)
det_a = a32 * (-1)**(3+2) 

[[-4 -3]
 [-2 -5]]


In [566]:
det_a = a32 * (minor3[0][0]*minor3[1][1]-minor3[0][1]*minor3[1][0])

In [567]:
det_a

np.int64(-28)

In [568]:
# testing with np.linalg.det
det_a_np = np.linalg.det(A)
print(round(det_a_np))

28
