### **Mathematical understanding of tensor operations**

#### 1) **Element wise operations**

Tensor -> it's higher dimension vector such as 2D >

Matrix with m,n can be interpreted as 2d -tensor

In [2]:
import numpy as np

##### Considering one of the activation functions such as __ReLU__:

In [65]:
x = np.arange(10).reshape(5,2)
y = np.arange(10).reshape(5,2)
def naive_element_wise_addition(x,y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
  
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] +=y[i,j]
    return x

In [77]:
print(f"X:\n{x}\n{'*'*10}\nY:\n{y}")

X:
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
**********
Y:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [78]:
z = naive_element_wise_addition(x,y)
print(z)

[[ 0  3]
 [ 6  9]
 [12 15]
 [18 21]
 [24 27]]


#### 2) **Broadcasting**

Previous naive_element_wise_addition supports operation between vectors only when the are of the same shape.

In Neural Networks Dense Layer, we will add 2D tensor with a vector. What if the shapes are different?

- 1) The smaller tensor will broadcast into the larger one ( if no ambiguity )

- 2) __Axes__ are added to a smaller tensor to match the __ndim__ of the larger tensor

- 3) The smaler tensor is repeated alongside these new axces to match full shape of the larger tensor

In [119]:
x = np.arange(21).reshape(3,-1)
x.ndim
y = np.array([14,15,16])
y.shape

(3,)

In [125]:
# X is 2D tensor
# y is 1d vector

# Broadcasting vector into tensor shape
# y.shape (3,) -> (1,3)

def naive_matrix_vector(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] +=y[i]
    return z




In [127]:
z = naive_matrix_vector(x,y)
z

array([[  0.,  14.,  28.,  42.,  56.,  70.,  84.],
       [105., 120., 135., 150., 165., 180., 195.],
       [224., 240., 256., 272., 288., 304., 320.]])

#### 3) **Tensor dot @**

Most useful tensor operation ( not to be confused with element wise dot product such as skalar (1,) @ vector(4,)  for example.)

In [135]:
x = np.array([1,2,3])
y = np.array([3,4,5])

In [131]:
def naive_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]

    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [138]:
z = naive_vector_dot(x,y)
print(z)

26


The Dot product between __vectors__ is a SCALAR

Only vectors with same number of elements are compatible for the Dot product!

#### 3.1) **Dot product between matrix and vector**:

In [146]:
x = np.arange(6).reshape(2,3)
y = np.arange(3).reshape(3,)

In [160]:
def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1

    assert x.shape[1] == y.shape[0]

    z = np.zeros_like(x.shape)

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z += x[i,j] * y[i]
    return z

In [161]:
z = naive_matrix_vector_dot(x,y)
print(z)

[12 12]


#### 3.2) **Dot product between 2 matrix**:

We can take the dot product between 2 matrices only and only if x.shape[1] == y.shape[0]

i.e only if column of first matrix match the row of second matrix

In [164]:
x = np.arange(20).reshape(10,2)
y = np.arange(10).reshape(2,-1)

In [185]:
def naive_matrix_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2

    assert x.shape[1] == y.shape[0] # IMPORTANT!

    z = np.zeros(shape=(x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            z[i,j] =naive_vector_dot(x[i,:], y[:,j])
    return z

In [186]:
z = naive_matrix_dot(x,y)
z

array([[  5.,   6.,   7.,   8.,   9.],
       [ 15.,  20.,  25.,  30.,  35.],
       [ 25.,  34.,  43.,  52.,  61.],
       [ 35.,  48.,  61.,  74.,  87.],
       [ 45.,  62.,  79.,  96., 113.],
       [ 55.,  76.,  97., 118., 139.],
       [ 65.,  90., 115., 140., 165.],
       [ 75., 104., 133., 162., 191.],
       [ 85., 118., 151., 184., 217.],
       [ 95., 132., 169., 206., 243.]])