### Principal Component Analysis

#### __1) Dimensionality reduction__

####  When faced with a large set of corre- lated variables, principal components allow us to summarize this set with a smaller number of representative variables that collectively explain most of the variability in the original 

#### PCA directions are represented as directions in the **feature space** along which the original data are __highly variable__

### __2) Visualization__

#### If we have a data __n x p__ where n= number of observations and p = number of features, in EDA, we would like to visualize scatterplot.

#### If number of feature is 10 , and we examine 2D scatterplot of the data , we will end up with (p /2) = p * (p-1)/2 => 45 scatterplots!

#### if __p is large__, we will not be able to look at all of them, and most of them will not be informative because each one of them contain just a small fraction of total infromation present in the data set.

#### Considering this case, we would like to find a low-dimensional representation of data that captures as much information as possible.

#### __INTUITION__: 

- each of n observations lives in a p dimensional space, but not all dimensions are intersting.

- PCA seeks small number of dimensions, where the "interesting" part is measured by the amount that the observations vary along each dimension

- Each dimension of PCA is linear combination of _p_ features

#### __Example 1__:

In [32]:
import numpy as np
import random
# making a 5 x 10 matrix

mat = np.random.randint(-5,50,50).reshape(5,10)
mat

array([[35, 20, 33, 47, 46,  3, 27, 28,  4, 23],
       [ 4, 41, -5, 46, 14, 33,  6, 33, 12, 37],
       [30, 13, 40, 46, 40, 10, 48, 43, -3,  2],
       [-3, 11, 42,  1, 27, 39, 26, 27, 40, 25],
       [27, 24, 12,  0, 13,  1,  4, 18, 48, 47]], dtype=int32)

### Making the covariance matrix S 

- covariance is the measure of how two variables correlate to eachother

- positive score indicates that variables are correlated, meaning that they move in the same direction

- my matrix is shape of (5,10). To make covariance matrix i will use the S:

### S  = 1 / n - 1 * np.dot(Xc,Xc.T)

- 1 / n - 1 because we derive covariance from the sample of population

- Xc means that our sample is centered which i will do manually 

we can not multiply the native shape 5,10 x 5,10 because inner dimmensions need to match

if we have 5 features, covariance matrix will be 5x5 matrix:


In [90]:
cov_matrix = np.dot(mat,mat.T) / mat.shape[0] - 1
print(cov_matrix.shape)
print(cov_matrix)

(5, 5)
[[1820.2 1136.  1838.2 1019.   860.4]
 [1136.  1551.2 1039.8  877.4  835. ]
 [1838.2 1039.8 2129.2 1116.6  608.6]
 [1019.   877.4 1116.6 1554.   951.4]
 [ 860.4  835.   608.6  951.4 1293.4]]


In [95]:
#print(cov_matrix)
# needs to be centered:

# Xc = Xij - mean(Xj)

# row 1
# current = 2 1 1 1 2
# current = 4 2 2 2 4
# current = 7 3 6 5 5
# 
def center(mat):
    print(mat.shape)
    result_mat = np.zeros(shape=mat.shape,dtype=float)
    row_sum = 0
    for rows in range(mat.shape[0]):
        print(mat[rows])
        for j in mat[rows]:
            row_sum += mat[rows]
            total = j - row_sum
            break

        
        
  
z = center(cov_matrix)

(5, 5)
[1820.2 1136.  1838.2 1019.   860.4]
[1136.  1551.2 1039.8  877.4  835. ]
[1838.2 1039.8 2129.2 1116.6  608.6]
[1019.   877.4 1116.6 1554.   951.4]
[ 860.4  835.   608.6  951.4 1293.4]
